# Generated by Django 5.2.1 on 2025-06-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarieties',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
